/* 
  NOTE: this config is auto generated by server process
  DO NOT MODIFY THIS FILE
*/
const config = {
  "host": {
    "name": "Christophe",
    "fileServerURL": "/fileServer",
    "statusURL": "/fileServer/Users/Christophe_status.json"
  },
  "remoteHost": {
    "NUC": "192.168.178.25:7575"
  },
  "htmlDiv": {
    "mainDiv": "mainDiv",
    "graphDiv": "diagram",
    "paletteDiv": "palette",
    "nodePaletteDiv": "nodePalette",
    "linePaletteDiv": "linkPalette"
  },
  "graph": {
    "isDoubleClickCreateNodeEnabled": false,
    "allowDeleteKey": true,
    "colorschema": "light",
    "defaultDSL": "DefaultDSL",
    "rootGraphURL": "/fileServer/graphRoot.json",
    "rootGraphNodeData": {
      "key": "Root Graph",
      "isDir": true,
      "fileURL": "/fileServer/graphRoot.json",
      "fileType": "text/json"
    },
    "maxHistoryLength": 30
  },
  "server": {
    "ip": "192.168.0.25"
  }
};