/* 
  NOTE: this config is auto generated by server process
  DO NOT MODIFY THIS FILE
*/
const config = {
  "host": {
    "name": "Frank",
    "fileServerURL": "/fileServer",
    "fileServerSystemURL": "/fileServer/System",
    "fileStatusURL": "/fileStatus",
    "statusURL": "/fileServer/Users/Frank_status.json"
  },
  "remoteHost": {},
  "htmlDiv": {
    "mainDiv": "mainDiv",
    "graphDiv": "diagram",
    "paletteDiv": "palette",
    "nodePaletteDiv": "nodePalette",
    "groupPaletteDiv": "groupPalette",
    "linkPaletteDiv": "linkPalette"
  },
  "graph": {
    "isDoubleClickCreateNodeEnabled": false,
    "allowDeleteKey": true,
    "colorSchema": "light",
    "defaultDSL": "DefaultDSL",
    "rootGraphURL": "/fileServer/graphRoot.json",
    "rootGraphNodeData": {
      "key": "Root Graph",
      "isDir": true,
      "fileURL": "/fileServer/graphRoot.json",
      "fileType": "text/json"
    },
    "maxHistoryLength": 30
  },
  "server": {
    "ip": "192.168.1.84"
  }
};