/* 
  NOTE: this config is auto generated by server process
  DO NOT MODIFY THIS FILE
*/
const config = {
  "client": {
    "host": {
      "name": "Antonello",
      "fileServerURL": "/fileServer",
      "fileServerSystemURL": "/fileServer/System",
      "fileStatusURL": "/fileStatus",
      "statusURL": "/fileServer/Users/Antonello_status.json"
    },
    "remoteHost": {
      "NUC": "192.168.1.11:7575"
    },
    "htmlDiv": {
      "mainDiv": "mainDiv",
      "graphDiv": "diagram",
      "paletteDiv": "palette",
      "nodePaletteDiv": "nodePalette",
      "groupPaletteDiv": "groupPalette",
      "linkPaletteDiv": "linkPalette"
    },
    "graph": {
      "isDoubleClickCreateNodeEnabled": true,
      "allowDeleteKey": false,
      "colorSchema": "dark",
      "zoomFactor": 1.05,
      "defaultDSL": "DefaultDSL",
      "rootGraphURL": "/fileServer/graphRoot.json",
      "rootGraphNodeData": {
        "key": "Root Graph",
        "isDir": true,
        "fileURL": "/fileServer/graphRoot.json",
        "fileType": "text/json"
      },
      "maxHistoryLength": 30
    },
    "server": {
      "ip": "192.168.1.12"
    }
  },
  "server": {
    "debugOnFileContentOn": true,
    "dataRoot": "../../../../../../Dropbox/DevAll/MDDToolsDataRoot",
    "deployRoot": "../../../../../../Dropbox/DevAll/MDDToolsDeployRoot",
    "tempRoot": "../../../../../../Dropbox/DevAll/MDDToolsTempRoot",
    "clientPath": "../client",
    "libPath": "../client/lib",
    "scriptPath": "../script",
    "testPath": "../test",
    "scriptPlatform": "linux",
    "webServerProtocol": "http",
    "webServerName": "localhost",
    "webServerPort": 80,
    "webSocketURL": "ws://localhost",
    "ssl": {
      "enabled": false,
      "key": "server.key",
      "cert": "server.cert"
    },
    "ip": "192.168.1.12"
  },
  "host": {
    "uid": 501,
    "gid": 20,
    "username": "antonelloceravola",
    "homedir": "/Users/antonelloceravola",
    "shell": "/bin/zsh",
    "hostname": "Antonellos-Mini",
    "platform": "darwin",
    "platformOS": "MacOS",
    "platformType": "linux"
  }
};
module.exports = config;