/* 
  NOTE: this config is auto generated by server process
  DO NOT MODIFY THIS FILE
*/
const config = {
  "client": {
    "host": {
      "name": "Frank",
      "fileServerURL": "/fileServer",
      "fileServerSystemURL": "/fileServer/System",
      "fileStatusURL": "/fileStatus",
      "statusURL": "/fileServer/Users/Frank_status.json"
    },
    "remoteHost": {},
    "htmlDiv": {
      "mainDiv": "mainDiv",
      "graphDiv": "diagram",
      "paletteDiv": "palette",
      "nodePaletteDiv": "nodePalette",
      "groupPaletteDiv": "groupPalette",
      "linkPaletteDiv": "linkPalette"
    },
    "graph": {
      "isDoubleClickCreateNodeEnabled": false,
      "allowDeleteKey": false,
      "colorSchema": "light",
      "zoomFactor": 1.25,
      "defaultDSL": "DefaultDSL",
      "rootGraphURL": "/fileServer/graphRoot.json",
      "rootGraphNodeData": {
        "key": "Root Graph",
        "isDir": true,
        "fileURL": "/fileServer/graphRoot.json",
        "fileType": "text/json"
      },
      "maxHistoryLength": 30
    },
    "server": {
      "ip": "172.26.3.127"
    }
  },
  "server": {
    "debugOnFileContentOn": true,
    "dataRoot": "../../../../../../Dropbox/DevAll/MDDToolsDataRoot",
    "deployRoot": "../../../../../../Dropbox/DevAll/MDDToolsDeployRoot",
    "tempRoot": "../../../../../../Dropbox/DevAll/MDDToolsTempRoot",
    "clientPath": "../client",
    "libPath": "../client/lib",
    "scriptPath": "../script",
    "testPath": "../test",
    "scriptPlatform": "win32",
    "webServerProtocol": "http",
    "webServerName": "localhost",
    "webServerPort": 80,
    "webSocketURL": "ws://localhost",
    "jwtSecretKey": "jwt_key_secret123",
    "ssl": {
      "enabled": false,
      "key": "server.key",
      "cert": "server.cert"
    },
    "ip": "172.26.3.127"
  },
  "host": {
    "uid": -1,
    "gid": -1,
    "username": "RE900106",
    "homedir": "C:\\Users\\RE900106",
    "shell": null,
    "hostname": "EHRIEXPS-77-DL",
    "platform": "win32",
    "platformOS": "Windows",
    "platformType": "windows"
  }
};

module.exports = config;